const express = require('express');
const bodyParser = require('body-parser');
const session = require('express-session');
const sqlite3 = require('sqlite3').verbose();

const app = express();
const PORT = 3000;

// Middleware
app.use(bodyParser.json());
app.use(session({
    secret: 'super-secret-session-key',
    resave: false,
    saveUninitialized: true,
    cookie: { secure: false } // Set to true if using HTTPS
}));

// In-memory database for demonstration
const db = new sqlite3.Database(':memory:');

// Initialize database table
db.serialize(() => {
    db.run("CREATE TABLE IF NOT EXISTS comments (id INTEGER PRIMARY KEY AUTOINCREMENT, content TEXT, user_id TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)");
});

// POST /api/comments
app.post('/api/comments', (req, res) => {
    // 1. Enforce maximum comment length
    const maxCommentLength = 500;
    const content = req.body.content;

    if (!content || content.length > maxCommentLength) {
        return res.status(400).json({ error: 'Comment must be between 1 and 500 characters.' });
    }

    // 2. Associate with authenticated user's session ID (not from request body)
    // We use req.sessionID which is generated by express-session
    const userId = req.sessionID;

    // 3. Use a parameterized query to prevent SQL Injection
    const sql = "INSERT INTO comments (content, user_id) VALUES (?, ?)";

    db.run(sql, [content, userId], function(err) {
        if (err) {
            console.error(err);
            return res.status(500).json({ error: 'Database error occurred.' });
        }
        res.status(201).json({ id: this.lastID, message: 'Comment posted successfully.' });
    });
});

app.listen(PORT, () => {
    console.log(`Server running on http://localhost:${PORT}`);
});